spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/c4demo?serverTimezone=GMT%2b8&useUnicode=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true
server:
  port: 8181


validator: SampleValidator
secret: C4demo

userName: c4_usr_048
password: 1qaz@WSX_048
